### ISSUE TITLE
css not loading after build on netlify

### ISSUE THREAD

**Issue by CDaCoW** [CodeStitchOfficial/Intermediate-Website-Kit-SASS#8]
![image](https://github.com/CodeStitchOfficial/Intermediate-Website-Kit-SASS/assets/139243287/149f5a0a-0dbb-4c60-bbcb-996e6cbcb45f)

css not loaded, <head> balise is grey (not loaded ?) 
no build error or in nav console

**Comment by CDaCoW** [comment]
edit : the bug was with the kit that you give in your freelancer tuto, this one (sass) work great

**Comment by jwhughes-work** [comment]
@CDaCoW how did you fix
